import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// clickprovider

 import { ClerkProvider } from '@clerk/nextjs'
import ToastProvier from './provider/ToastProvier'
import ConfettiProvider from '@/components/modals/confetti-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className}>
        <ConfettiProvider />
       <ToastProvier />
        
        {children}</body>
    </html>
    </ClerkProvider>
  )
}
